### PR TITLE
Add worker pool library.

### PR DESCRIPTION
**Pull request by patrickdappollonio**
## Description

Adds a library to create a worker pool queue pattern.

## Related Issue(s)

Fixes #

### CODE REVIEW

**Review by fharper — DISMISSED** [review]
Since it's a public repository, it's missing the LICENSE

**Comment by patrickdappollonio** [comment]
For things that are not much code but housekeeping, I'm happy to take a PR from you @fharper 😆

**Comment by patrickdappollonio** [comment]
Actually, I'll just copy the one you committed to dropkick. Hold.

**Comment by fharper** [comment]
Please do, it's everyone responsibilities to be sure that when they create a new repository, they had the proper license.

**Comment by patrickdappollonio** [comment]
Pro tip then: I'll add you a story to add the license to the default template for GitOps, that way every new repo is guaranteed to be created with the LICENSE file in it.

**Review by CristhianF7 — APPROVED** [review]

**Pull request merged**
